apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: books-api
  name: books-api
  namespace: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
        - image: tommilehtisaari/books-and-authors-graphql:sha-4773110
          name: books-api
