apiVersion: v1
kind: Service
metadata:
  labels:
    app: books-api
  name: books-api
  namespace: books
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: books-api
  type: ClusterIP
